#!/bin/bash

echo -e '\033]2;pegvoice\007'
exec nodemon \
  --ext 'ts,pegjs,pegvoice' \
  --delay 100ms \
  -w ~/pegvoice \
  --exec "$(dirname $0)/src/main.ts" \
    --server \
    --debug-log="~/.pegvoice/debug.log"
