#!/bin/bash

cd "$(dirname $0)"
echo -e '\033]2;pegvoice\007'
exec nodemon \
  --ext 'ts,pegjs,pegvoice' \
  --delay 100ms \
  -w ~/pegvoice \
  --exec "./src/main.ts" \
    --server \
    --debug-log="~/.pegvoice/debug.log"
