#!/bin/bash

cd "$(dirname $0)"
echo -e '\033]2;pegvoice\007'
exec "./node_modules/.bin/nodemon" \
  --ext 'ts,pegjs,pegvoice' \
  --delay 100ms \
  --signal SIGHUP \
  -w "." \
  -- "./src/main.ts" \
    --json-rpc=voice-server \
    --debug-log="~/.pegvoice/debug.log" \
    --use-old-if-broken \
    "$@"
