#!/bin/bash

echo -e '\033]2;pegvoice\007'
cd "$(dirname $0)"
exec nodemon \
  --ext 'ts,pegjs,pegvoice' \
  --delay 100ms \
  --signal SIGHUP \
  -w "." \
  --exec "./src/main.ts" \
    --debug-log="~/.pegvoice/debug.log" \
    --single-line \
    --use-old-if-broken \
    "$@"

