#!/bin/bash

echo -e '\033]2;pegvoice\007'
exec nodemon \
  --ext 'js,pegjs,pegvoice' \
  --delay 100ms \
  -w ~/pegvoice \
  --exec "$(dirname $0)/src/main.js" \
    --server \
    --debug-log="$(dirname $0)/debug.log" \
    --result-log="$(dirname $0)/samples/josh.sample"

