#!/bin/bash

echo -e '\033]2;pegvoice\007'
cd "$(dirname $0)"
exec nodemon \
  --ext 'ts,pegjs,pegvoice' \
  --delay 100ms \
  -w ~/pegvoice \
  --exec "./src/main.ts" \
    --server \
    --debug-log="~/.pegvoice/debug.log" \
    --single-line

